### ISSUE TITLE
Saving without values throws NullReferenceException on ParseText

### ISSUE THREAD

**Issue by darklajid** [nreco/AhoCorasickDoubleArrayTrie#3]
I was hoping that I could drop the values, since I only need to know start/end of the match in the input. But if I ````Save```` with saveValues set to false and later ````Load```` and call ````ParseText```` a NullReferenceException is thrown for me.

Is that a thing that should work?

**Comment by VitaliyMF** [comment]
What do you mean with "drop the values"? Save/Load methods allow you to serialize state machine that used to match list of keywords passed to Aho-Corasick search algorithm.

If you need to match another set of keywords just re-create `AhoCorasickDoubleArrayTrie` instance with new list of keywords, this is rather fast operation.

**Comment by darklajid** [comment]
trie.Save takes two parameters, the stream and a flag. Based on the name and the usage in the tests I assume that setting it to false is supposed to save disk space.

If I set that to false and later Load (deserialize) the trie, ParseText throws. If I set that parameter to true and Load the trie from disk, ParseText works as intended.

**Comment by VitaliyMF** [comment]
yeah it seems Save with saveValues:false works but something is not finished for this case in Load as there is no way to initialize `V[] v` array at this moment. This can be fixed with one more overload for load smth like

`public void Load(Stream input, Func<int,V> loadValue)`

where loadValue is delegate that resolves value associated with keyword by index as it goes in original collection of (key,value) pairs.

Until that you can use AhoCorasickDoubleArrayTrie<int> and Save with saveValues:true, and resolve real associated object on your side by this index.

**Comment by darklajid** [comment]
That's what I'm doing atm.. I just wanted to report the error ;)
No big deal for this scenario, but I wasn't sure if that's unintended/ a bug myself.

Thanks
